repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.54.1
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go.
        entry: golangci-lint run --new-from-rev ~ --fix
        types: [ go ]
        language: golang
        require_serial: true
        pass_filenames: false