// Code generated by hero.
// source: /Users/astec/go_workspace/src/bitbucket.com/asterus/debtstracker-server/gae_app/debtstracker/website/pages/inspector/contact-card.html
// DO NOT EDIT!
package inspector

import (
	"bytes"
	"time"

	"github.com/shiyanhui/hero"
)

func heroContactCard(now time.Time, contact contactWithBalances, buffer *bytes.Buffer) {
	buffer.WriteString(`
<div class="card mr-2 mb-2">
    <div class=card-body>
        <h4 class=card-title><a href="contact?id=`)
	hero.FormatInt(int64(contact.ID), buffer)
	buffer.WriteString(`">`)
	hero.EscapeHTML(contact.FullName(), buffer)
	buffer.WriteString(`</a></h4>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Status</th>
                <th scope="col">Telegram #</th>
                <th scope="col" class=center>Linked</th>
                <th scope="col" class="d">Transfers</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>`)
	hero.EscapeHTML(contact.Status, buffer)
	buffer.WriteString(`</td>

                `)
	if contact.TelegramUserID == 0 {
		buffer.WriteString(`
                <td>no</td>
                `)
	} else {
		buffer.WriteString(`
                <td>yes</td>
                `)
	}
	if contact.CounterpartyCounterpartyID == 0 {
		buffer.WriteString(`
                <td class=center>no</td>
                `)
	} else {
		buffer.WriteString(`
                <td class=center><a href=contact?id=`)
		hero.FormatInt(int64(contact.CounterpartyCounterpartyID), buffer)
		buffer.WriteString(`yes</a></td>
                `)
	}
	buffer.WriteString(`
                <td class="d">`)
	hero.FormatInt(int64(contact.transfersCount), buffer)
	buffer.WriteString(`</td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="container-fluid">
        <div class="row">
            `)

	renderContactBalance(contact.ID, "Balance (no interest)", contact.balances.withoutInterest, true,
		buffer)
	renderContactBalance(contact.ID, "Balance with interest", contact.balances.withInterest, false,
		buffer)

	buffer.WriteString(`
        </div>
    </div>
</div>
`)

}
