// Code generated by hero.
// source: /Users/astec/go_workspace/src/bitbucket.com/asterus/debtstracker-server/gae_app/debtstracker/website/pages/inspector/contact-card-balance.html
// DO NOT EDIT!
package inspector

import (
	"bytes"
	"fmt"

	"bitbucket.com/asterus/debtstracker-server/gae_app/debtstracker/models"
	"github.com/shiyanhui/hero"
)

func heroContactBalance(title string, balance models.Balance, buffer *bytes.Buffer) {
	if len(balance) > 0 {
		buffer.WriteString(`
<div class=col-sm>
    <table class="table table-striped">
        <thead>
        <tr>
            <th colspan=2 nowrap>`)
		hero.EscapeHTML(title, buffer)
		buffer.WriteString(`</th>
        </tr>
        </thead>
        <tbody>
        `)
		for currency, value := range balance {
			buffer.WriteString(`
        <tr>
            <td>`)
			hero.EscapeHTML(fmt.Sprintf("%v", currency), buffer)
			buffer.WriteString(`</td>
            <td class=d>`)
			hero.EscapeHTML(fmt.Sprintf("%v", value), buffer)
			buffer.WriteString(`</td>
        </tr>
        `)
		}
		buffer.WriteString(`
        </tbody>
    </table>
</div>
`)
	}

}
