// Code generated by hero.
// source: /Users/astec/go_workspace/src/bitbucket.org/asterus/debtstracker-server/gae_app/debtstracker/website/pages/inspector/layout.html
// DO NOT EDIT!
package inspector
