// Code generated by hero.
// source: /Users/astec/go_workspace/src/bitbucket.com/asterus/debtstracker-server/gae_app/debtstracker/website/pages/inspector/user-balance.html
// DO NOT EDIT!
package inspector

import (
	"bytes"
	"fmt"

	"github.com/shiyanhui/hero"
)

func renderUserBalance(title string, balances balancesByCurrency, showTransfers bool, buf *bytes.Buffer) {
	buf.WriteString(`
<div class="col-sm">
    <h3>`)
	hero.EscapeHTML(title, buf)
	buf.WriteString(`</h3>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Currency</th>
            <th class=d>User</th>
            <th class=d>Contacts</th>
            `)
	if showTransfers {
		buf.WriteString(`
            <th class=d>Transfers</th>
            `)
	}
	buf.WriteString(`
        </tr>
        </thead>
        <tbody>
        `)
	for currency, balance := range balances.byCurrency {
		buf.WriteString(`
        <tr>
            <td>`)
		hero.EscapeHTML(fmt.Sprintf("%v", currency), buf)
		buf.WriteString(`</td>
            <td class=d>`)
		hero.EscapeHTML(fmt.Sprintf("%v", balance.user), buf)
		buf.WriteString(`</td>
            <td class=d>`)
		hero.EscapeHTML(fmt.Sprintf("%v", balance.contacts), buf)
		buf.WriteString(`</td>
            `)
		if showTransfers {
			buf.WriteString(`
            <td class=d>`)
			hero.EscapeHTML(fmt.Sprintf("%v", balance.transfers), buf)
			buf.WriteString(`</td>
            `)
		}
		buf.WriteString(`
        </tr>
        `)
	}
	buf.WriteString(`
        </tbody>
    </table>
</div>`)

}
