// DO NOT EDIT!
// Code generated by ffjson <https://github.com/pquerna/ffjson>
// source: auth_google.go
// DO NOT EDIT!

package api

import (
	"bytes"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

func (mj *GoogleAuthData) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if mj == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := mj.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (mj *GoogleAuthData) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if mj == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{"userId":`)
	fflib.WriteJsonString(buf, string(mj.UserId))
	buf.WriteString(`,"displayName":`)
	fflib.WriteJsonString(buf, string(mj.DisplayName))
	buf.WriteString(`,"refreshToken":`)
	fflib.WriteJsonString(buf, string(mj.RefreshToken))
	buf.WriteString(`,"email":`)
	fflib.WriteJsonString(buf, string(mj.Email))
	buf.WriteString(`,"serverAuthCode":`)
	fflib.WriteJsonString(buf, string(mj.ServerAuthCode))
	buf.WriteString(`,"accessToken":`)
	fflib.WriteJsonString(buf, string(mj.AccessToken))
	buf.WriteString(`,"imageUrl":`)
	fflib.WriteJsonString(buf, string(mj.ImageUrl))
	buf.WriteString(`,"idToken":`)
	fflib.WriteJsonString(buf, string(mj.IdToken))
	buf.WriteByte('}')
	return nil
}

const (
	ffj_t_GoogleAuthDatabase = iota
	ffj_t_GoogleAuthDatano_such_key

	ffj_t_GoogleAuthData_UserId

	ffj_t_GoogleAuthData_DisplayName

	ffj_t_GoogleAuthData_RefreshToken

	ffj_t_GoogleAuthData_Email

	ffj_t_GoogleAuthData_ServerAuthCode

	ffj_t_GoogleAuthData_AccessToken

	ffj_t_GoogleAuthData_ImageUrl

	ffj_t_GoogleAuthData_IdToken
)

var ffj_key_GoogleAuthData_UserId = []byte("userId")

var ffj_key_GoogleAuthData_DisplayName = []byte("displayName")

var ffj_key_GoogleAuthData_RefreshToken = []byte("refreshToken")

var ffj_key_GoogleAuthData_Email = []byte("email")

var ffj_key_GoogleAuthData_ServerAuthCode = []byte("serverAuthCode")

var ffj_key_GoogleAuthData_AccessToken = []byte("accessToken")

var ffj_key_GoogleAuthData_ImageUrl = []byte("imageUrl")

var ffj_key_GoogleAuthData_IdToken = []byte("idToken")

func (uj *GoogleAuthData) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return uj.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

func (uj *GoogleAuthData) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error = nil
	currentKey := ffj_t_GoogleAuthDatabase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffj_t_GoogleAuthDatano_such_key
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 'a':

					if bytes.Equal(ffj_key_GoogleAuthData_AccessToken, kn) {
						currentKey = ffj_t_GoogleAuthData_AccessToken
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'd':

					if bytes.Equal(ffj_key_GoogleAuthData_DisplayName, kn) {
						currentKey = ffj_t_GoogleAuthData_DisplayName
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'e':

					if bytes.Equal(ffj_key_GoogleAuthData_Email, kn) {
						currentKey = ffj_t_GoogleAuthData_Email
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'i':

					if bytes.Equal(ffj_key_GoogleAuthData_ImageUrl, kn) {
						currentKey = ffj_t_GoogleAuthData_ImageUrl
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_GoogleAuthData_IdToken, kn) {
						currentKey = ffj_t_GoogleAuthData_IdToken
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'r':

					if bytes.Equal(ffj_key_GoogleAuthData_RefreshToken, kn) {
						currentKey = ffj_t_GoogleAuthData_RefreshToken
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 's':

					if bytes.Equal(ffj_key_GoogleAuthData_ServerAuthCode, kn) {
						currentKey = ffj_t_GoogleAuthData_ServerAuthCode
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'u':

					if bytes.Equal(ffj_key_GoogleAuthData_UserId, kn) {
						currentKey = ffj_t_GoogleAuthData_UserId
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				}

				if fflib.EqualFoldRight(ffj_key_GoogleAuthData_IdToken, kn) {
					currentKey = ffj_t_GoogleAuthData_IdToken
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_GoogleAuthData_ImageUrl, kn) {
					currentKey = ffj_t_GoogleAuthData_ImageUrl
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_GoogleAuthData_AccessToken, kn) {
					currentKey = ffj_t_GoogleAuthData_AccessToken
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_GoogleAuthData_ServerAuthCode, kn) {
					currentKey = ffj_t_GoogleAuthData_ServerAuthCode
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_GoogleAuthData_Email, kn) {
					currentKey = ffj_t_GoogleAuthData_Email
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_GoogleAuthData_RefreshToken, kn) {
					currentKey = ffj_t_GoogleAuthData_RefreshToken
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_GoogleAuthData_DisplayName, kn) {
					currentKey = ffj_t_GoogleAuthData_DisplayName
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_GoogleAuthData_UserId, kn) {
					currentKey = ffj_t_GoogleAuthData_UserId
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				currentKey = ffj_t_GoogleAuthDatano_such_key
				state = fflib.FFParse_want_colon
				goto mainparse
			}

		case fflib.FFParse_want_colon:
			if tok != fflib.FFTok_colon {
				wantedTok = fflib.FFTok_colon
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_value
			continue
		case fflib.FFParse_want_value:

			if tok == fflib.FFTok_left_brace || tok == fflib.FFTok_left_bracket || tok == fflib.FFTok_integer || tok == fflib.FFTok_double || tok == fflib.FFTok_string || tok == fflib.FFTok_bool || tok == fflib.FFTok_null {
				switch currentKey {

				case ffj_t_GoogleAuthData_UserId:
					goto handle_UserId

				case ffj_t_GoogleAuthData_DisplayName:
					goto handle_DisplayName

				case ffj_t_GoogleAuthData_RefreshToken:
					goto handle_RefreshToken

				case ffj_t_GoogleAuthData_Email:
					goto handle_Email

				case ffj_t_GoogleAuthData_ServerAuthCode:
					goto handle_ServerAuthCode

				case ffj_t_GoogleAuthData_AccessToken:
					goto handle_AccessToken

				case ffj_t_GoogleAuthData_ImageUrl:
					goto handle_ImageUrl

				case ffj_t_GoogleAuthData_IdToken:
					goto handle_IdToken

				case ffj_t_GoogleAuthDatano_such_key:
					err = fs.SkipField(tok)
					if err != nil {
						return fs.WrapErr(err)
					}
					state = fflib.FFParse_after_value
					goto mainparse
				}
			} else {
				goto wantedvalue
			}
		}
	}

handle_UserId:

	/* handler: uj.UserId type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.UserId = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_DisplayName:

	/* handler: uj.DisplayName type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.DisplayName = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_RefreshToken:

	/* handler: uj.RefreshToken type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.RefreshToken = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Email:

	/* handler: uj.Email type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Email = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_ServerAuthCode:

	/* handler: uj.ServerAuthCode type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.ServerAuthCode = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_AccessToken:

	/* handler: uj.AccessToken type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.AccessToken = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_ImageUrl:

	/* handler: uj.ImageUrl type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.ImageUrl = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_IdToken:

	/* handler: uj.IdToken type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.IdToken = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

wantedvalue:
	return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
wrongtokenerror:
	return fs.WrapErr(fmt.Errorf("ffjson: wanted token: %v, but got token: %v output=%s", wantedTok, tok, fs.Output.String()))
tokerror:
	if fs.BigError != nil {
		return fs.WrapErr(fs.BigError)
	}
	err = fs.Error.ToError()
	if err != nil {
		return fs.WrapErr(err)
	}
	panic("ffjson-generated: unreachable, please report bug.")
done:

	return nil
}
