// DO NOT EDIT!
// Code generated by ffjson <https://github.com/pquerna/ffjson>
// source: transfer_fromto.go
// DO NOT EDIT!

package models

import (
	"bytes"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

func (mj *TransferCounterpartyInfo) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if mj == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := mj.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (mj *TransferCounterpartyInfo) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if mj == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{ `)
	if mj.UserID != 0 {
		buf.WriteString(`"UserID":`)
		fflib.FormatBits2(buf, uint64(mj.UserID), 10, mj.UserID < 0)
		buf.WriteByte(',')
	}
	if len(mj.UserName) != 0 {
		buf.WriteString(`"Name":`)
		fflib.WriteJsonString(buf, string(mj.UserName))
		buf.WriteByte(',')
	}
	if mj.ContactID != 0 {
		buf.WriteString(`"ContactID":`)
		fflib.FormatBits2(buf, uint64(mj.ContactID), 10, mj.ContactID < 0)
		buf.WriteByte(',')
	}
	if len(mj.ContactName) != 0 {
		buf.WriteString(`"ContactName":`)
		fflib.WriteJsonString(buf, string(mj.ContactName))
		buf.WriteByte(',')
	}
	if len(mj.Note) != 0 {
		buf.WriteString(`"Note":`)
		fflib.WriteJsonString(buf, string(mj.Note))
		buf.WriteByte(',')
	}
	if len(mj.Comment) != 0 {
		buf.WriteString(`"Comment":`)
		fflib.WriteJsonString(buf, string(mj.Comment))
		buf.WriteByte(',')
	}
	buf.Rewind(1)
	buf.WriteByte('}')
	return nil
}

const (
	ffj_t_TransferCounterpartyInfobase = iota
	ffj_t_TransferCounterpartyInfono_such_key

	ffj_t_TransferCounterpartyInfo_UserID

	ffj_t_TransferCounterpartyInfo_UserName

	ffj_t_TransferCounterpartyInfo_CounterpartyID

	ffj_t_TransferCounterpartyInfo_CounterpartyName

	ffj_t_TransferCounterpartyInfo_Note

	ffj_t_TransferCounterpartyInfo_Comment
)

var ffj_key_TransferCounterpartyInfo_UserID = []byte("UserID")

var ffj_key_TransferCounterpartyInfo_UserName = []byte("Name")

var ffj_key_TransferCounterpartyInfo_CounterpartyID = []byte("ContactID")

var ffj_key_TransferCounterpartyInfo_CounterpartyName = []byte("ContactName")

var ffj_key_TransferCounterpartyInfo_Note = []byte("Note")

var ffj_key_TransferCounterpartyInfo_Comment = []byte("Comment")

func (uj *TransferCounterpartyInfo) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return uj.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

func (uj *TransferCounterpartyInfo) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error = nil
	currentKey := ffj_t_TransferCounterpartyInfobase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffj_t_TransferCounterpartyInfono_such_key
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 'C':

					if bytes.Equal(ffj_key_TransferCounterpartyInfo_CounterpartyID, kn) {
						currentKey = ffj_t_TransferCounterpartyInfo_CounterpartyID
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_TransferCounterpartyInfo_CounterpartyName, kn) {
						currentKey = ffj_t_TransferCounterpartyInfo_CounterpartyName
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_TransferCounterpartyInfo_Comment, kn) {
						currentKey = ffj_t_TransferCounterpartyInfo_Comment
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'N':

					if bytes.Equal(ffj_key_TransferCounterpartyInfo_Note, kn) {
						currentKey = ffj_t_TransferCounterpartyInfo_Note
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'U':

					if bytes.Equal(ffj_key_TransferCounterpartyInfo_UserID, kn) {
						currentKey = ffj_t_TransferCounterpartyInfo_UserID
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_TransferCounterpartyInfo_UserName, kn) {
						currentKey = ffj_t_TransferCounterpartyInfo_UserName
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				}

				if fflib.SimpleLetterEqualFold(ffj_key_TransferCounterpartyInfo_Comment, kn) {
					currentKey = ffj_t_TransferCounterpartyInfo_Comment
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_TransferCounterpartyInfo_Note, kn) {
					currentKey = ffj_t_TransferCounterpartyInfo_Note
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_TransferCounterpartyInfo_CounterpartyName, kn) {
					currentKey = ffj_t_TransferCounterpartyInfo_CounterpartyName
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_TransferCounterpartyInfo_CounterpartyID, kn) {
					currentKey = ffj_t_TransferCounterpartyInfo_CounterpartyID
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_TransferCounterpartyInfo_UserName, kn) {
					currentKey = ffj_t_TransferCounterpartyInfo_UserName
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_TransferCounterpartyInfo_UserID, kn) {
					currentKey = ffj_t_TransferCounterpartyInfo_UserID
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				currentKey = ffj_t_TransferCounterpartyInfono_such_key
				state = fflib.FFParse_want_colon
				goto mainparse
			}

		case fflib.FFParse_want_colon:
			if tok != fflib.FFTok_colon {
				wantedTok = fflib.FFTok_colon
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_value
			continue
		case fflib.FFParse_want_value:

			if tok == fflib.FFTok_left_brace || tok == fflib.FFTok_left_bracket || tok == fflib.FFTok_integer || tok == fflib.FFTok_double || tok == fflib.FFTok_string || tok == fflib.FFTok_bool || tok == fflib.FFTok_null {
				switch currentKey {

				case ffj_t_TransferCounterpartyInfo_UserID:
					goto handle_UserID

				case ffj_t_TransferCounterpartyInfo_UserName:
					goto handle_UserName

				case ffj_t_TransferCounterpartyInfo_CounterpartyID:
					goto handle_CounterpartyID

				case ffj_t_TransferCounterpartyInfo_CounterpartyName:
					goto handle_CounterpartyName

				case ffj_t_TransferCounterpartyInfo_Note:
					goto handle_Note

				case ffj_t_TransferCounterpartyInfo_Comment:
					goto handle_Comment

				case ffj_t_TransferCounterpartyInfono_such_key:
					err = fs.SkipField(tok)
					if err != nil {
						return fs.WrapErr(err)
					}
					state = fflib.FFParse_after_value
					goto mainparse
				}
			} else {
				goto wantedvalue
			}
		}
	}

handle_UserID:

	/* handler: uj.UserID type=int64 kind=int64 quoted=false*/

	{
		if tok != fflib.FFTok_integer && tok != fflib.FFTok_null {
			return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for int64", tok))
		}
	}

	{

		if tok == fflib.FFTok_null {

		} else {

			tval, err := fflib.ParseInt(fs.Output.Bytes(), 10, 64)

			if err != nil {
				return fs.WrapErr(err)
			}

			uj.UserID = int64(tval)

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_UserName:

	/* handler: uj.Name type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.UserName = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_CounterpartyID:

	/* handler: uj.ContactID type=int64 kind=int64 quoted=false*/

	{
		if tok != fflib.FFTok_integer && tok != fflib.FFTok_null {
			return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for int64", tok))
		}
	}

	{

		if tok == fflib.FFTok_null {

		} else {

			tval, err := fflib.ParseInt(fs.Output.Bytes(), 10, 64)

			if err != nil {
				return fs.WrapErr(err)
			}

			uj.ContactID = int64(tval)

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_CounterpartyName:

	/* handler: uj.ContactName type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.ContactName = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Note:

	/* handler: uj.Note type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Note = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Comment:

	/* handler: uj.Comment type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Comment = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

wantedvalue:
	return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
wrongtokenerror:
	return fs.WrapErr(fmt.Errorf("ffjson: wanted token: %v, but got token: %v output=%s", wantedTok, tok, fs.Output.String()))
tokerror:
	if fs.BigError != nil {
		return fs.WrapErr(fs.BigError)
	}
	err = fs.Error.ToError()
	if err != nil {
		return fs.WrapErr(err)
	}
	panic("ffjson-generated: unreachable, please report bug.")
done:

	return nil
}
