// DO NOT EDIT!
// Code generated by ffjson <https://github.com/pquerna/ffjson>
// source: user_contact_json.go
// DO NOT EDIT!

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
	interest "github.com/crediterra/go-interest"
)

// MarshalJSON marshal bytes to json - template
func (j *LastTransfer) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *LastTransfer) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{"ID":`)
	fflib.FormatBits2(buf, uint64(j.ID), 10, j.ID < 0)
	buf.WriteString(`,"At":`)

	{

		obj, err = j.At.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteByte('}')
	return nil
}

const (
	ffjtLastTransferbase = iota
	ffjtLastTransfernosuchkey

	ffjtLastTransferID

	ffjtLastTransferAt
)

var ffjKeyLastTransferID = []byte("ID")

var ffjKeyLastTransferAt = []byte("At")

// UnmarshalJSON umarshall json - template of ffjson
func (j *LastTransfer) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return j.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

// UnmarshalJSONFFLexer fast json unmarshall - template ffjson
func (j *LastTransfer) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error
	currentKey := ffjtLastTransferbase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffjtLastTransfernosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 'A':

					if bytes.Equal(ffjKeyLastTransferAt, kn) {
						currentKey = ffjtLastTransferAt
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'I':

					if bytes.Equal(ffjKeyLastTransferID, kn) {
						currentKey = ffjtLastTransferID
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				}

				if fflib.SimpleLetterEqualFold(ffjKeyLastTransferAt, kn) {
					currentKey = ffjtLastTransferAt
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffjKeyLastTransferID, kn) {
					currentKey = ffjtLastTransferID
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				currentKey = ffjtLastTransfernosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			}

		case fflib.FFParse_want_colon:
			if tok != fflib.FFTok_colon {
				wantedTok = fflib.FFTok_colon
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_value
			continue
		case fflib.FFParse_want_value:

			if tok == fflib.FFTok_left_brace || tok == fflib.FFTok_left_bracket || tok == fflib.FFTok_integer || tok == fflib.FFTok_double || tok == fflib.FFTok_string || tok == fflib.FFTok_bool || tok == fflib.FFTok_null {
				switch currentKey {

				case ffjtLastTransferID:
					goto handle_ID

				case ffjtLastTransferAt:
					goto handle_At

				case ffjtLastTransfernosuchkey:
					err = fs.SkipField(tok)
					if err != nil {
						return fs.WrapErr(err)
					}
					state = fflib.FFParse_after_value
					goto mainparse
				}
			} else {
				goto wantedvalue
			}
		}
	}

handle_ID:

	/* handler: j.ID type=int64 kind=int64 quoted=false*/

	{
		if tok != fflib.FFTok_integer && tok != fflib.FFTok_null {
			return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for int64", tok))
		}
	}

	{

		if tok == fflib.FFTok_null {

		} else {

			tval, err := fflib.ParseInt(fs.Output.Bytes(), 10, 64)

			if err != nil {
				return fs.WrapErr(err)
			}

			j.ID = int64(tval)

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_At:

	/* handler: j.At type=time.Time kind=struct quoted=false*/

	{
		if tok == fflib.FFTok_null {

			state = fflib.FFParse_after_value
			goto mainparse
		}

		tbuf, err := fs.CaptureField(tok)
		if err != nil {
			return fs.WrapErr(err)
		}

		err = j.At.UnmarshalJSON(tbuf)
		if err != nil {
			return fs.WrapErr(err)
		}
		state = fflib.FFParse_after_value
	}

	state = fflib.FFParse_after_value
	goto mainparse

wantedvalue:
	return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
wrongtokenerror:
	return fs.WrapErr(fmt.Errorf("ffjson: wanted token: %v, but got token: %v output=%s", wantedTok, tok, fs.Output.String()))
tokerror:
	if fs.BigError != nil {
		return fs.WrapErr(fs.BigError)
	}
	err = fs.Error.ToError()
	if err != nil {
		return fs.WrapErr(err)
	}
	panic("ffjson-generated: unreachable, please report bug.")
done:

	return nil
}

// MarshalJSON marshal bytes to json - template
func (j *TransferWithInterestJson) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *TransferWithInterestJson) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{ "TransferID":`)
	fflib.FormatBits2(buf, uint64(j.TransferID), 10, j.TransferID < 0)
	buf.WriteString(`,"Direction":`)
	fflib.WriteJsonString(buf, string(j.Direction))
	buf.WriteString(`,"Starts":`)

	{

		obj, err = j.Starts.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"Currency":`)
	fflib.WriteJsonString(buf, string(j.Currency))
	buf.WriteString(`,"Amount":`)

	{

		obj, err = j.Amount.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteByte(',')
	if len(j.Returns) != 0 {
		buf.WriteString(`"Returns":`)
		if j.Returns != nil {
			buf.WriteString(`[`)
			for i, v := range j.Returns {
				if i != 0 {
					buf.WriteString(`,`)
				}

				{

					err = v.MarshalJSONBuf(buf)
					if err != nil {
						return err
					}

				}
			}
			buf.WriteString(`]`)
		} else {
			buf.WriteString(`null`)
		}
		buf.WriteByte(',')
	}
	buf.WriteString(`"InterestType":`)
	fflib.WriteJsonString(buf, string(j.InterestType))
	buf.WriteString(`,"InterestPeriod":`)
	fflib.FormatBits2(buf, uint64(j.InterestPeriod), 10, j.InterestPeriod < 0)
	buf.WriteString(`,"InterestPercent":`)

	{

		obj, err = j.InterestPercent.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteByte(',')
	if j.InterestGracePeriod != 0 {
		buf.WriteString(`"InterestGracePeriod":`)
		fflib.FormatBits2(buf, uint64(j.InterestGracePeriod), 10, j.InterestGracePeriod < 0)
		buf.WriteByte(',')
	}
	if j.InterestMinimumPeriod != 0 {
		buf.WriteString(`"InterestMinimumPeriod":`)
		fflib.FormatBits2(buf, uint64(j.InterestMinimumPeriod), 10, j.InterestMinimumPeriod < 0)
		buf.WriteByte(',')
	}
	buf.Rewind(1)
	buf.WriteByte('}')
	return nil
}

const (
	ffjtTransferWithInterestJsonbase = iota
	ffjtTransferWithInterestJsonnosuchkey

	ffjtTransferWithInterestJsonTransferID

	ffjtTransferWithInterestJsonDirection

	ffjtTransferWithInterestJsonStarts

	ffjtTransferWithInterestJsonCurrency

	ffjtTransferWithInterestJsonAmount

	ffjtTransferWithInterestJsonReturns

	ffjtTransferWithInterestJsonInterestType

	ffjtTransferWithInterestJsonInterestPeriod

	ffjtTransferWithInterestJsonInterestPercent

	ffjtTransferWithInterestJsonInterestGracePeriod

	ffjtTransferWithInterestJsonInterestMinimumPeriod
)

var ffjKeyTransferWithInterestJsonTransferID = []byte("TransferID")

var ffjKeyTransferWithInterestJsonDirection = []byte("Direction")

var ffjKeyTransferWithInterestJsonStarts = []byte("Starts")

var ffjKeyTransferWithInterestJsonCurrency = []byte("Currency")

var ffjKeyTransferWithInterestJsonAmount = []byte("Amount")

var ffjKeyTransferWithInterestJsonReturns = []byte("Returns")

var ffjKeyTransferWithInterestJsonInterestType = []byte("InterestType")

var ffjKeyTransferWithInterestJsonInterestPeriod = []byte("InterestPeriod")

var ffjKeyTransferWithInterestJsonInterestPercent = []byte("InterestPercent")

var ffjKeyTransferWithInterestJsonInterestGracePeriod = []byte("InterestGracePeriod")

var ffjKeyTransferWithInterestJsonInterestMinimumPeriod = []byte("InterestMinimumPeriod")

// UnmarshalJSON umarshall json - template of ffjson
func (j *TransferWithInterestJson) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return j.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

// UnmarshalJSONFFLexer fast json unmarshall - template ffjson
func (j *TransferWithInterestJson) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error
	currentKey := ffjtTransferWithInterestJsonbase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffjtTransferWithInterestJsonnosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 'A':

					if bytes.Equal(ffjKeyTransferWithInterestJsonAmount, kn) {
						currentKey = ffjtTransferWithInterestJsonAmount
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'C':

					if bytes.Equal(ffjKeyTransferWithInterestJsonCurrency, kn) {
						currentKey = ffjtTransferWithInterestJsonCurrency
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'D':

					if bytes.Equal(ffjKeyTransferWithInterestJsonDirection, kn) {
						currentKey = ffjtTransferWithInterestJsonDirection
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'I':

					if bytes.Equal(ffjKeyTransferWithInterestJsonInterestType, kn) {
						currentKey = ffjtTransferWithInterestJsonInterestType
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffjKeyTransferWithInterestJsonInterestPeriod, kn) {
						currentKey = ffjtTransferWithInterestJsonInterestPeriod
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffjKeyTransferWithInterestJsonInterestPercent, kn) {
						currentKey = ffjtTransferWithInterestJsonInterestPercent
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffjKeyTransferWithInterestJsonInterestGracePeriod, kn) {
						currentKey = ffjtTransferWithInterestJsonInterestGracePeriod
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffjKeyTransferWithInterestJsonInterestMinimumPeriod, kn) {
						currentKey = ffjtTransferWithInterestJsonInterestMinimumPeriod
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'R':

					if bytes.Equal(ffjKeyTransferWithInterestJsonReturns, kn) {
						currentKey = ffjtTransferWithInterestJsonReturns
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'S':

					if bytes.Equal(ffjKeyTransferWithInterestJsonStarts, kn) {
						currentKey = ffjtTransferWithInterestJsonStarts
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'T':

					if bytes.Equal(ffjKeyTransferWithInterestJsonTransferID, kn) {
						currentKey = ffjtTransferWithInterestJsonTransferID
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				}

				if fflib.EqualFoldRight(ffjKeyTransferWithInterestJsonInterestMinimumPeriod, kn) {
					currentKey = ffjtTransferWithInterestJsonInterestMinimumPeriod
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyTransferWithInterestJsonInterestGracePeriod, kn) {
					currentKey = ffjtTransferWithInterestJsonInterestGracePeriod
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyTransferWithInterestJsonInterestPercent, kn) {
					currentKey = ffjtTransferWithInterestJsonInterestPercent
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyTransferWithInterestJsonInterestPeriod, kn) {
					currentKey = ffjtTransferWithInterestJsonInterestPeriod
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyTransferWithInterestJsonInterestType, kn) {
					currentKey = ffjtTransferWithInterestJsonInterestType
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyTransferWithInterestJsonReturns, kn) {
					currentKey = ffjtTransferWithInterestJsonReturns
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffjKeyTransferWithInterestJsonAmount, kn) {
					currentKey = ffjtTransferWithInterestJsonAmount
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffjKeyTransferWithInterestJsonCurrency, kn) {
					currentKey = ffjtTransferWithInterestJsonCurrency
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyTransferWithInterestJsonStarts, kn) {
					currentKey = ffjtTransferWithInterestJsonStarts
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffjKeyTransferWithInterestJsonDirection, kn) {
					currentKey = ffjtTransferWithInterestJsonDirection
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyTransferWithInterestJsonTransferID, kn) {
					currentKey = ffjtTransferWithInterestJsonTransferID
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				currentKey = ffjtTransferWithInterestJsonnosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			}

		case fflib.FFParse_want_colon:
			if tok != fflib.FFTok_colon {
				wantedTok = fflib.FFTok_colon
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_value
			continue
		case fflib.FFParse_want_value:

			if tok == fflib.FFTok_left_brace || tok == fflib.FFTok_left_bracket || tok == fflib.FFTok_integer || tok == fflib.FFTok_double || tok == fflib.FFTok_string || tok == fflib.FFTok_bool || tok == fflib.FFTok_null {
				switch currentKey {

				case ffjtTransferWithInterestJsonTransferID:
					goto handle_TransferID

				case ffjtTransferWithInterestJsonDirection:
					goto handle_Direction

				case ffjtTransferWithInterestJsonStarts:
					goto handle_Starts

				case ffjtTransferWithInterestJsonCurrency:
					goto handle_Currency

				case ffjtTransferWithInterestJsonAmount:
					goto handle_Amount

				case ffjtTransferWithInterestJsonReturns:
					goto handle_Returns

				case ffjtTransferWithInterestJsonInterestType:
					goto handle_InterestType

				case ffjtTransferWithInterestJsonInterestPeriod:
					goto handle_InterestPeriod

				case ffjtTransferWithInterestJsonInterestPercent:
					goto handle_InterestPercent

				case ffjtTransferWithInterestJsonInterestGracePeriod:
					goto handle_InterestGracePeriod

				case ffjtTransferWithInterestJsonInterestMinimumPeriod:
					goto handle_InterestMinimumPeriod

				case ffjtTransferWithInterestJsonnosuchkey:
					err = fs.SkipField(tok)
					if err != nil {
						return fs.WrapErr(err)
					}
					state = fflib.FFParse_after_value
					goto mainparse
				}
			} else {
				goto wantedvalue
			}
		}
	}

handle_TransferID:

	/* handler: j.TransferID type=int64 kind=int64 quoted=false*/

	{
		if tok != fflib.FFTok_integer && tok != fflib.FFTok_null {
			return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for int64", tok))
		}
	}

	{

		if tok == fflib.FFTok_null {

		} else {

			tval, err := fflib.ParseInt(fs.Output.Bytes(), 10, 64)

			if err != nil {
				return fs.WrapErr(err)
			}

			j.TransferID = int64(tval)

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Direction:

	/* handler: j.Direction type=models.TransferDirection kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for TransferDirection", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			j.Direction = TransferDirection(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Starts:

	/* handler: j.Starts type=time.Time kind=struct quoted=false*/

	{
		if tok == fflib.FFTok_null {

			state = fflib.FFParse_after_value
			goto mainparse
		}

		tbuf, err := fs.CaptureField(tok)
		if err != nil {
			return fs.WrapErr(err)
		}

		err = j.Starts.UnmarshalJSON(tbuf)
		if err != nil {
			return fs.WrapErr(err)
		}
		state = fflib.FFParse_after_value
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Currency:

	/* handler: j.Currency type=models.Currency kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for Currency", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			j.Currency = Currency(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Amount:

	/* handler: j.Amount type=decimal.Decimal64p2 kind=int64 quoted=false*/

	{
		if tok == fflib.FFTok_null {

			state = fflib.FFParse_after_value
			goto mainparse
		}

		tbuf, err := fs.CaptureField(tok)
		if err != nil {
			return fs.WrapErr(err)
		}

		err = j.Amount.UnmarshalJSON(tbuf)
		if err != nil {
			return fs.WrapErr(err)
		}
		state = fflib.FFParse_after_value
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Returns:

	/* handler: j.Returns type=[]models.TransferReturnJson kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			j.Returns = nil
		} else {

			j.Returns = []TransferReturnJson{}

			wantVal := true

			for {

				var tmpJReturns TransferReturnJson

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: tmpJReturns type=models.TransferReturnJson kind=struct quoted=false*/

				{
					if tok == fflib.FFTok_null {

						state = fflib.FFParse_after_value
						goto mainparse
					}

					err = tmpJReturns.UnmarshalJSONFFLexer(fs, fflib.FFParse_want_key)
					if err != nil {
						return err
					}
					state = fflib.FFParse_after_value
				}

				j.Returns = append(j.Returns, tmpJReturns)

				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_InterestType:

	/* handler: j.InterestType type=models.InterestPercentType kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for InterestPercentType", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			j.InterestType = interest.Formula(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_InterestPeriod:

	/* handler: j.InterestPeriod type=int kind=int quoted=false*/

	{
		if tok != fflib.FFTok_integer && tok != fflib.FFTok_null {
			return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for int", tok))
		}
	}

	{

		if tok == fflib.FFTok_null {

		} else {

			tval, err := fflib.ParseInt(fs.Output.Bytes(), 10, 64)

			if err != nil {
				return fs.WrapErr(err)
			}

			j.InterestPeriod = interest.RatePeriodInDays(tval)

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_InterestPercent:

	/* handler: j.InterestPercent type=decimal.Decimal64p2 kind=int64 quoted=false*/

	{
		if tok == fflib.FFTok_null {

			state = fflib.FFParse_after_value
			goto mainparse
		}

		tbuf, err := fs.CaptureField(tok)
		if err != nil {
			return fs.WrapErr(err)
		}

		err = j.InterestPercent.UnmarshalJSON(tbuf)
		if err != nil {
			return fs.WrapErr(err)
		}
		state = fflib.FFParse_after_value
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_InterestGracePeriod:

	/* handler: j.InterestGracePeriod type=int kind=int quoted=false*/

	{
		if tok != fflib.FFTok_integer && tok != fflib.FFTok_null {
			return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for int", tok))
		}
	}

	{

		if tok == fflib.FFTok_null {

		} else {

			tval, err := fflib.ParseInt(fs.Output.Bytes(), 10, 64)

			if err != nil {
				return fs.WrapErr(err)
			}

			j.InterestGracePeriod = int(tval)

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_InterestMinimumPeriod:

	/* handler: j.InterestMinimumPeriod type=int kind=int quoted=false*/

	{
		if tok != fflib.FFTok_integer && tok != fflib.FFTok_null {
			return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for int", tok))
		}
	}

	{

		if tok == fflib.FFTok_null {

		} else {

			tval, err := fflib.ParseInt(fs.Output.Bytes(), 10, 64)

			if err != nil {
				return fs.WrapErr(err)
			}

			j.InterestMinimumPeriod = int(tval)

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

wantedvalue:
	return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
wrongtokenerror:
	return fs.WrapErr(fmt.Errorf("ffjson: wanted token: %v, but got token: %v output=%s", wantedTok, tok, fs.Output.String()))
tokerror:
	if fs.BigError != nil {
		return fs.WrapErr(fs.BigError)
	}
	err = fs.Error.ToError()
	if err != nil {
		return fs.WrapErr(err)
	}
	panic("ffjson-generated: unreachable, please report bug.")
done:

	return nil
}

// MarshalJSON marshal bytes to json - template
func (j *UserContactJson) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *UserContactJson) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{ "ID":`)
	fflib.FormatBits2(buf, uint64(j.ID), 10, j.ID < 0)
	buf.WriteString(`,"Name":`)
	fflib.WriteJsonString(buf, string(j.Name))
	buf.WriteByte(',')
	if len(j.Status) != 0 {
		buf.WriteString(`"Status":`)
		fflib.WriteJsonString(buf, string(j.Status))
		buf.WriteByte(',')
	}
	if j.UserID != 0 {
		buf.WriteString(`"UserID":`)
		fflib.FormatBits2(buf, uint64(j.UserID), 10, j.UserID < 0)
		buf.WriteByte(',')
	}
	if j.TgUserID != 0 {
		buf.WriteString(`"TgUserID":`)
		fflib.FormatBits2(buf, uint64(j.TgUserID), 10, j.TgUserID < 0)
		buf.WriteByte(',')
	}
	if j.BalanceJson != nil {
		if true {
			buf.WriteString(`"Balance":`)

			{

				obj, err = j.BalanceJson.MarshalJSON()
				if err != nil {
					return err
				}
				buf.Write(obj)

			}
			buf.WriteByte(',')
		}
	}
	if j.Transfers != nil {
		if true {
			buf.WriteString(`"Transfers":`)

			{

				err = j.Transfers.MarshalJSONBuf(buf)
				if err != nil {
					return err
				}

			}
			buf.WriteByte(',')
		}
	}
	buf.Rewind(1)
	buf.WriteByte('}')
	return nil
}

const (
	ffjtUserContactJsonbase = iota
	ffjtUserContactJsonnosuchkey

	ffjtUserContactJsonID

	ffjtUserContactJsonName

	ffjtUserContactJsonStatus

	ffjtUserContactJsonUserID

	ffjtUserContactJsonTgUserID

	ffjtUserContactJsonBalanceJson

	ffjtUserContactJsonTransfers
)

var ffjKeyUserContactJsonID = []byte("ID")

var ffjKeyUserContactJsonName = []byte("Name")

var ffjKeyUserContactJsonStatus = []byte("Status")

var ffjKeyUserContactJsonUserID = []byte("UserID")

var ffjKeyUserContactJsonTgUserID = []byte("TgUserID")

var ffjKeyUserContactJsonBalanceJson = []byte("Balance")

var ffjKeyUserContactJsonTransfers = []byte("Transfers")

// UnmarshalJSON umarshall json - template of ffjson
func (j *UserContactJson) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return j.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

// UnmarshalJSONFFLexer fast json unmarshall - template ffjson
func (j *UserContactJson) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error
	currentKey := ffjtUserContactJsonbase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffjtUserContactJsonnosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 'B':

					if bytes.Equal(ffjKeyUserContactJsonBalanceJson, kn) {
						currentKey = ffjtUserContactJsonBalanceJson
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'I':

					if bytes.Equal(ffjKeyUserContactJsonID, kn) {
						currentKey = ffjtUserContactJsonID
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'N':

					if bytes.Equal(ffjKeyUserContactJsonName, kn) {
						currentKey = ffjtUserContactJsonName
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'S':

					if bytes.Equal(ffjKeyUserContactJsonStatus, kn) {
						currentKey = ffjtUserContactJsonStatus
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'T':

					if bytes.Equal(ffjKeyUserContactJsonTgUserID, kn) {
						currentKey = ffjtUserContactJsonTgUserID
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffjKeyUserContactJsonTransfers, kn) {
						currentKey = ffjtUserContactJsonTransfers
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'U':

					if bytes.Equal(ffjKeyUserContactJsonUserID, kn) {
						currentKey = ffjtUserContactJsonUserID
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				}

				if fflib.EqualFoldRight(ffjKeyUserContactJsonTransfers, kn) {
					currentKey = ffjtUserContactJsonTransfers
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffjKeyUserContactJsonBalanceJson, kn) {
					currentKey = ffjtUserContactJsonBalanceJson
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyUserContactJsonTgUserID, kn) {
					currentKey = ffjtUserContactJsonTgUserID
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyUserContactJsonUserID, kn) {
					currentKey = ffjtUserContactJsonUserID
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyUserContactJsonStatus, kn) {
					currentKey = ffjtUserContactJsonStatus
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffjKeyUserContactJsonName, kn) {
					currentKey = ffjtUserContactJsonName
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffjKeyUserContactJsonID, kn) {
					currentKey = ffjtUserContactJsonID
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				currentKey = ffjtUserContactJsonnosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			}

		case fflib.FFParse_want_colon:
			if tok != fflib.FFTok_colon {
				wantedTok = fflib.FFTok_colon
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_value
			continue
		case fflib.FFParse_want_value:

			if tok == fflib.FFTok_left_brace || tok == fflib.FFTok_left_bracket || tok == fflib.FFTok_integer || tok == fflib.FFTok_double || tok == fflib.FFTok_string || tok == fflib.FFTok_bool || tok == fflib.FFTok_null {
				switch currentKey {

				case ffjtUserContactJsonID:
					goto handle_ID

				case ffjtUserContactJsonName:
					goto handle_Name

				case ffjtUserContactJsonStatus:
					goto handle_Status

				case ffjtUserContactJsonUserID:
					goto handle_UserID

				case ffjtUserContactJsonTgUserID:
					goto handle_TgUserID

				case ffjtUserContactJsonBalanceJson:
					goto handle_BalanceJson

				case ffjtUserContactJsonTransfers:
					goto handle_Transfers

				case ffjtUserContactJsonnosuchkey:
					err = fs.SkipField(tok)
					if err != nil {
						return fs.WrapErr(err)
					}
					state = fflib.FFParse_after_value
					goto mainparse
				}
			} else {
				goto wantedvalue
			}
		}
	}

handle_ID:

	/* handler: j.ID type=int64 kind=int64 quoted=false*/

	{
		if tok != fflib.FFTok_integer && tok != fflib.FFTok_null {
			return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for int64", tok))
		}
	}

	{

		if tok == fflib.FFTok_null {

		} else {

			tval, err := fflib.ParseInt(fs.Output.Bytes(), 10, 64)

			if err != nil {
				return fs.WrapErr(err)
			}

			j.ID = int64(tval)

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Name:

	/* handler: j.Name type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			j.Name = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Status:

	/* handler: j.Status type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			j.Status = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_UserID:

	/* handler: j.UserID type=int64 kind=int64 quoted=false*/

	{
		if tok != fflib.FFTok_integer && tok != fflib.FFTok_null {
			return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for int64", tok))
		}
	}

	{

		if tok == fflib.FFTok_null {

		} else {

			tval, err := fflib.ParseInt(fs.Output.Bytes(), 10, 64)

			if err != nil {
				return fs.WrapErr(err)
			}

			j.UserID = int64(tval)

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_TgUserID:

	/* handler: j.TgUserID type=int64 kind=int64 quoted=false*/

	{
		if tok != fflib.FFTok_integer && tok != fflib.FFTok_null {
			return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for int64", tok))
		}
	}

	{

		if tok == fflib.FFTok_null {

		} else {

			tval, err := fflib.ParseInt(fs.Output.Bytes(), 10, 64)

			if err != nil {
				return fs.WrapErr(err)
			}

			j.TgUserID = int64(tval)

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_BalanceJson:

	/* handler: j.BalanceJson type=json.RawMessage kind=slice quoted=false*/

	{
		if tok == fflib.FFTok_null {

			j.BalanceJson = nil

			state = fflib.FFParse_after_value
			goto mainparse
		}

		tbuf, err := fs.CaptureField(tok)
		if err != nil {
			return fs.WrapErr(err)
		}

		if j.BalanceJson == nil {
			j.BalanceJson = new(json.RawMessage)
		}

		err = j.BalanceJson.UnmarshalJSON(tbuf)
		if err != nil {
			return fs.WrapErr(err)
		}
		state = fflib.FFParse_after_value
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Transfers:

	/* handler: j.Transfers type=models.UserContactTransfersInfo kind=struct quoted=false*/

	{
		if tok == fflib.FFTok_null {

			j.Transfers = nil

			state = fflib.FFParse_after_value
			goto mainparse
		}

		if j.Transfers == nil {
			j.Transfers = new(UserContactTransfersInfo)
		}

		err = j.Transfers.UnmarshalJSONFFLexer(fs, fflib.FFParse_want_key)
		if err != nil {
			return err
		}
		state = fflib.FFParse_after_value
	}

	state = fflib.FFParse_after_value
	goto mainparse

wantedvalue:
	return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
wrongtokenerror:
	return fs.WrapErr(fmt.Errorf("ffjson: wanted token: %v, but got token: %v output=%s", wantedTok, tok, fs.Output.String()))
tokerror:
	if fs.BigError != nil {
		return fs.WrapErr(fs.BigError)
	}
	err = fs.Error.ToError()
	if err != nil {
		return fs.WrapErr(err)
	}
	panic("ffjson-generated: unreachable, please report bug.")
done:

	return nil
}

// MarshalJSON marshal bytes to json - template
func (j *UserContactTransfersInfo) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *UserContactTransfersInfo) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{ `)
	if j.Count != 0 {
		buf.WriteString(`"Count":`)
		fflib.FormatBits2(buf, uint64(j.Count), 10, j.Count < 0)
		buf.WriteByte(',')
	}
	if true {
		buf.WriteString(`"Last":`)

		{

			err = j.Last.MarshalJSONBuf(buf)
			if err != nil {
				return err
			}

		}
		buf.WriteByte(',')
	}
	if len(j.OutstandingWithInterest) != 0 {
		buf.WriteString(`"OutstandingWithInterest":`)
		if j.OutstandingWithInterest != nil {
			buf.WriteString(`[`)
			for i, v := range j.OutstandingWithInterest {
				if i != 0 {
					buf.WriteString(`,`)
				}

				{

					err = v.MarshalJSONBuf(buf)
					if err != nil {
						return err
					}

				}
			}
			buf.WriteString(`]`)
		} else {
			buf.WriteString(`null`)
		}
		buf.WriteByte(',')
	}
	buf.Rewind(1)
	buf.WriteByte('}')
	return nil
}

const (
	ffjtUserContactTransfersInfobase = iota
	ffjtUserContactTransfersInfonosuchkey

	ffjtUserContactTransfersInfoCount

	ffjtUserContactTransfersInfoLast

	ffjtUserContactTransfersInfoOutstandingWithInterest
)

var ffjKeyUserContactTransfersInfoCount = []byte("Count")

var ffjKeyUserContactTransfersInfoLast = []byte("Last")

var ffjKeyUserContactTransfersInfoOutstandingWithInterest = []byte("OutstandingWithInterest")

// UnmarshalJSON umarshall json - template of ffjson
func (j *UserContactTransfersInfo) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return j.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

// UnmarshalJSONFFLexer fast json unmarshall - template ffjson
func (j *UserContactTransfersInfo) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error
	currentKey := ffjtUserContactTransfersInfobase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffjtUserContactTransfersInfonosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 'C':

					if bytes.Equal(ffjKeyUserContactTransfersInfoCount, kn) {
						currentKey = ffjtUserContactTransfersInfoCount
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'L':

					if bytes.Equal(ffjKeyUserContactTransfersInfoLast, kn) {
						currentKey = ffjtUserContactTransfersInfoLast
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'O':

					if bytes.Equal(ffjKeyUserContactTransfersInfoOutstandingWithInterest, kn) {
						currentKey = ffjtUserContactTransfersInfoOutstandingWithInterest
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				}

				if fflib.EqualFoldRight(ffjKeyUserContactTransfersInfoOutstandingWithInterest, kn) {
					currentKey = ffjtUserContactTransfersInfoOutstandingWithInterest
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyUserContactTransfersInfoLast, kn) {
					currentKey = ffjtUserContactTransfersInfoLast
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffjKeyUserContactTransfersInfoCount, kn) {
					currentKey = ffjtUserContactTransfersInfoCount
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				currentKey = ffjtUserContactTransfersInfonosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			}

		case fflib.FFParse_want_colon:
			if tok != fflib.FFTok_colon {
				wantedTok = fflib.FFTok_colon
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_value
			continue
		case fflib.FFParse_want_value:

			if tok == fflib.FFTok_left_brace || tok == fflib.FFTok_left_bracket || tok == fflib.FFTok_integer || tok == fflib.FFTok_double || tok == fflib.FFTok_string || tok == fflib.FFTok_bool || tok == fflib.FFTok_null {
				switch currentKey {

				case ffjtUserContactTransfersInfoCount:
					goto handle_Count

				case ffjtUserContactTransfersInfoLast:
					goto handle_Last

				case ffjtUserContactTransfersInfoOutstandingWithInterest:
					goto handle_OutstandingWithInterest

				case ffjtUserContactTransfersInfonosuchkey:
					err = fs.SkipField(tok)
					if err != nil {
						return fs.WrapErr(err)
					}
					state = fflib.FFParse_after_value
					goto mainparse
				}
			} else {
				goto wantedvalue
			}
		}
	}

handle_Count:

	/* handler: j.Count type=int kind=int quoted=false*/

	{
		if tok != fflib.FFTok_integer && tok != fflib.FFTok_null {
			return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for int", tok))
		}
	}

	{

		if tok == fflib.FFTok_null {

		} else {

			tval, err := fflib.ParseInt(fs.Output.Bytes(), 10, 64)

			if err != nil {
				return fs.WrapErr(err)
			}

			j.Count = int(tval)

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Last:

	/* handler: j.Last type=models.LastTransfer kind=struct quoted=false*/

	{
		if tok == fflib.FFTok_null {

			state = fflib.FFParse_after_value
			goto mainparse
		}

		err = j.Last.UnmarshalJSONFFLexer(fs, fflib.FFParse_want_key)
		if err != nil {
			return err
		}
		state = fflib.FFParse_after_value
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_OutstandingWithInterest:

	/* handler: j.OutstandingWithInterest type=[]models.TransferWithInterestJson kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			j.OutstandingWithInterest = nil
		} else {

			j.OutstandingWithInterest = []TransferWithInterestJson{}

			wantVal := true

			for {

				var tmpJOutstandingWithInterest TransferWithInterestJson

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: tmpJOutstandingWithInterest type=models.TransferWithInterestJson kind=struct quoted=false*/

				{
					if tok == fflib.FFTok_null {

						state = fflib.FFParse_after_value
						goto mainparse
					}

					err = tmpJOutstandingWithInterest.UnmarshalJSONFFLexer(fs, fflib.FFParse_want_key)
					if err != nil {
						return err
					}
					state = fflib.FFParse_after_value
				}

				j.OutstandingWithInterest = append(j.OutstandingWithInterest, tmpJOutstandingWithInterest)

				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

wantedvalue:
	return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
wrongtokenerror:
	return fs.WrapErr(fmt.Errorf("ffjson: wanted token: %v, but got token: %v output=%s", wantedTok, tok, fs.Output.String()))
tokerror:
	if fs.BigError != nil {
		return fs.WrapErr(fs.BigError)
	}
	err = fs.Error.ToError()
	if err != nil {
		return fs.WrapErr(err)
	}
	panic("ffjson-generated: unreachable, please report bug.")
done:

	return nil
}
